#!/usr/bin/env python3
"""Embed Integration/guest payloads into the Macus library, or check they match.

Does not download an image, create state, or boot a VM.
"""
import argparse
import base64
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GUEST = ROOT / "Integration" / "guest"
CATALOG = ROOT / "Integration" / "catalog" / "alpine-3.24.2.json"
OUTPUT = ROOT / "Sources" / "Macus" / "Bootstrap" / "EmbeddedGuestPayload.swift"
FILES = (
    "bootstrap.sh",
    "bridge.py",
    "storage.sh",
    "tama-bootstrap.initd",
    "tama-bridge.initd",
    "tama-storage.initd",
)


def revision(payloads):
    digest = hashlib.sha256()
    for name in FILES:
        data = payloads[name]
        digest.update(name.encode())
        digest.update(b"\0")
        digest.update(str(len(data)).encode())
        digest.update(b"\0")
        digest.update(data)
    return digest.hexdigest()


def load():
    payloads = {}
    for name in FILES:
        payloads[name] = (GUEST / name).read_bytes()
    return payloads


def render(payloads):
    lines = [
        "// Generated by Integration/scripts/sync-guest-payload.py. Do not edit by hand.",
        "import Foundation",
        "",
        "enum EmbeddedGuestPayload {",
        f'  static let revision = "{revision(payloads)}"',
        "  static let files: [String: String] = [",
    ]
    for name in FILES:
        encoded = base64.b64encode(payloads[name]).decode()
        lines.append(f'    "{name}": """')
        for offset in range(0, len(encoded), 76):
            lines.append(f"    {encoded[offset:offset + 76]}")
        lines.append('    """,')
    lines.extend([
        "  ]",
        "",
        "  static func text(_ name: String) throws -> String {",
        "    guard let encoded = files[name] else {",
        '      throw RuntimeError(.io, "Missing embedded guest payload \\(name)")',
        "    }",
        "    let joined = String(encoded.unicodeScalars.filter { !$0.properties.isWhitespace })",
        "    guard let data = Data(base64Encoded: joined),",
        "      let text = String(data: data, encoding: .utf8)",
        "    else { throw RuntimeError(.io, \"Embedded guest payload \\(name) is corrupt\") }",
        "    return text",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.check == args.write:
        parser.error("Choose exactly one of --check or --write")
    payloads = load()
    rendered = render(payloads)
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            parser.error(f"{OUTPUT.relative_to(ROOT)} is out of sync with Integration/guest")
        print(revision(payloads))
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(OUTPUT)


if __name__ == "__main__":
    main()
